apiVersion: v1
kind: Service
metadata:
  name: fraud-detection-service
  namespace: fraud-detection-system
spec:
  type: NodePort
  selector:
    app: fraud-api
  ports:
    - port: 8000
      targetPort: 8000
      nodePort: 30001 # Exposing the API on port 30001 for the external world